name: Build Lyrical Ballads Site

on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Self checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build Docker image
        run: docker build . -t lyrical_ballads:latest

      - name: Build site
        run: |
          docker run \
            -v ${{ github.workspace }}:/var/www \
            lyrical_ballads:latest \
            ant -f build.xml

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ github.workspace }}/public

      - name: Deploy
        uses: actions/deploy-pages@v2
